package inputs;

public interface MouseCode {
    int GLFW_MOUSE_BUTTON_1 = 0;
    int GLFW_MOUSE_BUTTON_2 = 1;
    int GLFW_MOUSE_BUTTON_3 = 2;
    int GLFW_MOUSE_BUTTON_4 = 3;
    int GLFW_MOUSE_BUTTON_5 = 4;
    int GLFW_MOUSE_BUTTON_6 = 5;
    int GLFW_MOUSE_BUTTON_7 = 6;
    int GLFW_MOUSE_BUTTON_8 = 7;
    int GLFW_MOUSE_BUTTON_LAST = GLFW_MOUSE_BUTTON_8;
    int GLFW_MOUSE_BUTTON_LEFT = GLFW_MOUSE_BUTTON_1;
    int GLFW_MOUSE_BUTTON_RIGHT = GLFW_MOUSE_BUTTON_2;
    int GLFW_MOUSE_BUTTON_MIDDLE = GLFW_MOUSE_BUTTON_3;
}
